version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - echo Installing frontend dependencies...
      - npm install
      - echo Building APP
      - npm run build
      - cd ../
      - cp appspec.yml build/
      - chmod -R +x scripts/
      - cp -r scripts/ build/
      
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
  name: build.zip
